package utils

import (
	"JD/models"
	"encoding/json"
	"fmt"
	"io/ioutil"
)

var Au *models.AutoGenerated

func Init() *models.AutoGenerated {
	var au models.AutoGenerated

	content, err := ioutil.ReadFile("./config/Init.ini")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(content))
	if err != nil {
		fmt.Println(err)
	}

	err = json.Unmarshal(content, &au)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(au.Mysql.Word)
	Au = &au
	return Au
}
