package utils

import (
	"JD/models"
	"encoding/json"
	"fmt"
	"io/ioutil"
)

var au models.AutoGenerated

func Init() models.AutoGenerated {
	content, err := ioutil.ReadFile("./config/Init.ini")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(content))
	if err != nil {
		fmt.Println(err)
	}

	err = json.Unmarshal(content, &au)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(au.Mysql.Word)
	return au
}
