package utils

import (
	"JD/models"
	"encoding/json"
	"fmt"
	"io/ioutil"
)

var Au *models.AutoGenerated

func Init() *models.AutoGenerated {
	var au models.AutoGenerated

	content, err := ioutil.ReadFile("./config/Init.ini")
	if err != nil {
	}
	fmt.Println(string(content))

	err = json.Unmarshal(content, &au)

	Au = &au
	return Au
}
