package models

type AutoGenerated struct {
	Mysql Mysql `json:"mysql"`
	Sms   Sms   `json:"sms"`
	Redis Redis `json:"redis"`
}
type Mysql struct {
	User  string `json:"user"`
	Word  string `json:"word"`
	Bases string `json:"bases"`
}
type Sms struct {
	ID       string `json:"id"`
	Key      string `json:"key"`
	Smsid    string `json:"smsid"`
	Signname string `json:"signname"`
	Templeid string `json:"templeid"`
}
type Redis struct {
	Host   string `json:"host"`
	Port   string `json:"Port"`
	Passwd string `json:"passwd"`
}
